swamp-agr/watcher-bot

- config/default.dhall
- src/Watcher/Bot.hs
- src/Watcher/Bot/Cache.hs
- src/Watcher/Bot/Reply.hs
- src/Watcher/Bot/Settings.hs
- src/Watcher/Bot/State.hs
Bonus point: if bot restarted, you'll know about it.
> Report cache sizes on a daily basis

- src/Watcher/Bot/Handle/Setup.hs
- src/Watcher/Bot/Types/Action.hs
- Before: what done is done!
- After: Bot will send 2 updates: first about complete setup and second with Root menu again.
> Resume setup by resetting state machine

- src/Watcher/Bot/Reply.hs
Right now no reply is being originated.
> Send reply when entering multiple chats state

- config/migrations/02-poll-with-spam-message-id.dhall
- src/Watcher/Bot/Handle/Ban.hs
- src/Watcher/Bot/Handle/Message.hs
- src/Watcher/Bot/Reply.hs
- src/Watcher/Bot/State/Chat.hs
- src/Watcher/Bot/Types/Action.hs
- Delete spam message on consensus ban.
- Give bot a voice in case of absence of voter.
- Don't forget to share spam message with owners to train more data.
- Migration for PollState included.
> Improve poll UX

- src/Watcher/Bot/Handle/Setup.hs
Simplify write to `admins` cache
> Always override `admins`

- src/Watcher/Bot/Handle/Ban.hs
Don't allow opening poll against one of admins
> Prevent opening poll against admins

- src/Watcher/Bot/Reply.hs
...so that it does not render literal <a> tag inside the message
> Add HTML parse_mode for some replies

- src/Watcher/Bot/Handle/Message.hs
When bot receives update with a system message that user has joined the chat, they might be already banned elsewhere. We don't need to wait for the next message, just ban known spamer already.
> Check newcomers if they're already banned

- src/Watcher/Bot/Parse.hs
Repoint chat_member update on debug to collect kicks and understand them better
> Collect more info on chat_member updates

- src/Watcher/Bot/Parse.hs
Once again, fix parser ChatId but for SomeChatId.
> Fix SomeChatId parser

- config/dictionary.dhall
Extend dictionary. No need to rebuild the app
> Add USD and a few more words to dictionary

- src/Watcher/Bot/Handle/Ban.hs
it turns out, that users are inclined to consider themself as a spam
> Do not accept self-reports

- src/Watcher/Bot/Handle.hs
- src/Watcher/Bot/Handle/Debug.hs
- src/Watcher/Bot/Parse.hs
- src/Watcher/Bot/Types/Action.hs
The idea is to develop job that periodically loops through quarantine and updates chat and blocklist states.
> Add `/getChatMember` for debugging quarantine

- src/Watcher/Bot/Handle/Debug.hs
Right now it's impossible to verify whether people who's left are spamers or not
> Add more info to check spamers

- src/Watcher/Bot.hs
- src/Watcher/Bot/Analytics.hs
- src/Watcher/Bot/Handle.hs
- src/Watcher/Bot/Handle/Ban.hs
- src/Watcher/Bot/Handle/Contact.hs
- src/Watcher/Bot/Handle/Debug.hs
- src/Watcher/Bot/Handle/Dump.hs
- src/Watcher/Bot/Handle/Help.hs
- src/Watcher/Bot/Handle/Message.hs
- src/Watcher/Bot/Handle/Setup.hs
- src/Watcher/Bot/Handle/Unban.hs
- src/Watcher/Bot/ModelChecker.hs
- src/Watcher/Bot/Reply.hs
- src/Watcher/Bot/State.hs
- src/Watcher/Bot/Utils.hs
- Rewrite all code into ImplicitParams to fit one style.
> Rewrite everything in ImplicitParams

- src/Watcher/Bot/Handle/Ban.hs
> Poll hasn't changed when it was created

- src/Watcher/Bot/Handle/Ban.hs
Currently it's impossible to distinguish bot from user. This PR fixes it. New polls will contain a message starting with `Bot...` if user's message was recognised as most likely a spam.
> Change opening poll message when it's created by bot

- src/Watcher/Bot/Parse.hs
Do not drop `@` during username parser
> Fix username parser

- src/Watcher/Bot/Handle.hs
- src/Watcher/Bot/Handle/Setup.hs
- src/Watcher/Bot/Parse.hs
- src/Watcher/Bot/Types/Action.hs
Also, implement command specific for datafix
> Fix untitled chat in menu

- src/Watcher/Bot/Handle/Setup.hs
Use max of `Nothing` and `Just title` to resolve duplicates
> Add datafix function which removes duplicates

- src/Watcher/Bot/Handle.hs
- src/Watcher/Bot/Handle/Setup.hs
- src/Watcher/Bot/Parse.hs
- src/Watcher/Bot/Types/Action.hs
Datafix has been apllied. Command and job are no longer needed.
> Cleanup after datafix

- src/Watcher/Bot/Handle.hs
- src/Watcher/Bot/Handle/Unban.hs
- src/Watcher/Bot/Parse.hs
- src/Watcher/Bot/Types/Action.hs
> Datafix: fill in usernames of known spammers if possible

- src/Watcher/Bot/Handle/Ban.hs
Situation:
1. User replies with `/s`. Poll has been created.
2. Admin replies with `/s`. 
- ER: poll will become closed.
- AR: poll remains present.
This MR fixes race between two separate bans.
> Ensure poll is closed when admin is banning spammer separately

- src/Watcher/Bot/Handle.hs
- src/Watcher/Bot/Handle/Dump.hs
When it's over, reply with text
> Acknowledge when dump has been generated

- src/Watcher/Bot.hs
- src/Watcher/Bot/Handle/Dump.hs
- src/Watcher/Bot/Handle/Unban.hs
- src/Watcher/Bot/State.hs
- src/Watcher/Migration.hs
- watcher-bot.cabal
Prepare to import 250K CAS entries
> Move `spamerBans` from `HashMap` to concurrent `HashTable`

- src/Watcher/Bot/Cache.hs
- src/Watcher/Bot/Handle.hs
- src/Watcher/Bot/Handle/Dump.hs
At least, add extra message in case of reduced dump size
> Alert on reduced dump

- src/Watcher/Bot.hs
- Add the some logic to worker
> Reply with dump size comparisons even from background

- src/Watcher/Bot/Parse.hs
Some users requested this feature.
> Add пнх alias for spam command

- src/Watcher/Bot/Reply.hs
Before: quarantine term was confusing. With this PR it becomes more clear that user is not restricted but rather watched.
> Changed quarantine setup message

- src/Watcher/Bot/State.hs
Don't set lock for the entire retry chain of API calls. Relax it so the next event from other thread could be processed.
> Move lock outside of retries
