config/common/map.dhall, config/migrations/01-optional-chat-titles.dhall, src/Watcher/Bot/Handle/Setup.hs, src/Watcher/Bot/State/User.hs
Users that are admins in more than one chat struggle to use bot since lack of chat title and current code are not making possible to store the evidence in cache.
This PR is intended to fix it. Since it changes the shape of the cache, migration has been provided separately. 
Right now bot owner must apply migration manually. In the future, it must be automated via migration worker. Worker itself is out-of-scope of this PR.
=> Store chat titles, don't drop optional values

src/Watcher/Bot/Reply.hs
Callbacks shouldn't be enforced in root menu.
=> Don't enforce callback context in root menus

src/Watcher/Bot/Handle/Debug.hs, src/Watcher/Bot/Handle/Setup.hs, src/Watcher/Bot/Reply.hs, src/Watcher/Bot/Types/MessageFrom.hs
Replace boolean blindness with context provided by data constructors. All navigate-like messages are coming from callbacks. All setup checks are coming from replies.
=> Distinguish callbacks from replies

src/Watcher/Bot/Reply.hs
In callback parser we're trying to obtain `MenuId` but sending `ChatId`.
=> Send `MenuId` instead of `ChatId`

src/Watcher/Bot/Handle/Setup.hs
Right now (after #8, #9, #10, #11, #12, #13 and #14) there is a weird state where that same chat is present twice (with and without title).
This MR is intended to sort this mess out by overriding set value if chat title is present and get rid of duplicate. Bonus point: if group is not present in chat, it'd be added!
=> Replace chat title in `chatAdmins` if value is present

src/Watcher/Bot/Handle/Setup.hs
Self-explanatory: always refresh admins when /setup called.
=> Disable logic that prevents admins from being refreshed often

config/default.dhall, config/migrations/03-switch-self-destroy.dhall, src/Watcher/Bot/Handle/Ban.hs, src/Watcher/Bot/Handle/Message.hs, src/Watcher/Bot/Handle/Unban.hs, src/Watcher/Bot/Reply.hs, src/Watcher/Bot/Settings.hs, src/Watcher/Bot/State/Chat.hs, src/Watcher/Bot/Types/Action.hs
- Add setting which allows to turn self-destroyable messages off.
- Turn it on by default.
- Add migration for both users and groups.
=> Add setting that prevents sending self-destroyable messages

src/Watcher/Bot/Types/MessageFrom.hs
Right now detect function is looking at title (and it's wrong. It should look at chat_username.
=> Fix leaving private groups and channels

src/Watcher/Bot/Handle.hs, src/Watcher/Bot/Handle/Ban.hs, src/Watcher/Bot/Parse.hs, src/Watcher/Bot/Types/Action.hs, src/Watcher/Bot/Types/MessageFrom.hs
Potentially controversial one. Let bot listen of what other bots do and if they ban someone, add spamer to shared blocklist.
=> Listen for bans by other bot admins

src/Watcher/Bot/Parse.hs
It was discovered that tba's doc has became outdated at some point. As consequence, handleChatMember might be improved by listening for "kicked" status as well.
See more:
- https://core.telegram.org/bots/api#chatmemberbanned
- https://hackage.haskell.org/package/telegram-bot-api-7.4.2/docs/Telegram-Bot-API-Types-ChatMember.html#t:ChatMember
=> Support "kicked" chat member status

src/Watcher/Bot/Handle.hs, src/Watcher/Bot/Handle/Unban.hs, src/Watcher/Bot/Parse.hs, src/Watcher/Bot/Types/Action.hs, src/Watcher/Bot/Types/MessageFrom.hs
- Absence of banned chats should be counted for a global unban in a single group.
- Add `/unban` capability for owners to unban user globally everywhere user is banned.
=> Improve UX of unban

src/Watcher/Bot/Handle/Ban.hs, src/Watcher/Bot/Handle/Message.hs
Since BanState was extended there was overhaul with chat information. This MR fixes it.
=> Include chatId in ban state

src/Watcher/Bot/Parse.hs
Hypothesis: drop `@` character from the username and feed the rest to Bot API.
=> Fix unban by username

src/Watcher/Bot/Handle/Message.hs, src/Watcher/Bot/Parse.hs
- check for `messageNewChatMembers` before the actual check for message text.
- restore `updateChatMember` (no logs gathered)
=> Check for known spamers / quarantine before entering logic branches

src/Watcher/Bot/Handle.hs, src/Watcher/Bot/Handle/Debug.hs, src/Watcher/Bot/Handle/Message.hs, src/Watcher/Bot/Parse.hs, src/Watcher/Bot/Types/Action.hs
- Produce output for entire chat quarantine, just metadata: user status in the chat and amount of received messages
- Remove debug for already banned users
=> Improve response of `/getChatMember`

src/Watcher/Bot.hs, src/Watcher/Bot/Cache.hs, src/Watcher/Bot/Handle/Ban.hs, src/Watcher/Bot/Handle/Message.hs, src/Watcher/Bot/State.hs
If it turns out to be success, schedule it to run periodically.
- Traverse all chat states and clean up quarantine. According to Telegram Bot API "kicked"  means user is a spammer and it's banned, so no need to keep spammers in quarantine.
- Moreover, remove redundant exception handler from `call` and `liftClientM` which introduces unsafety for this bot.
=> Add one-time quarantine worker (autoban)

src/Watcher/Bot.hs, src/Watcher/Bot/Handle/Ban.hs, src/Watcher/Bot/Handle/Contact.hs, src/Watcher/Bot/Handle/Debug.hs, src/Watcher/Bot/Handle/Message.hs, src/Watcher/Bot/Handle/Setup.hs, src/Watcher/Bot/ModelChecker.hs, src/Watcher/Bot/State.hs, src/Watcher/Bot/Utils.hs, watcher-bot.cabal
Right now some of output has been lost due to buffering, worker threads and other causes. This PR intends to fix it by replacing `log'` with `katip`.
=> Add logger

config/default.dhall, src/Watcher/Bot.hs, src/Watcher/Bot/Handle.hs, src/Watcher/Bot/Handle/ChatMember.hs, src/Watcher/Bot/Handle/Dump.hs, src/Watcher/Bot/Handle/Message.hs, src/Watcher/Bot/Reply.hs, src/Watcher/Bot/Settings.hs, src/Watcher/Bot/State.hs, src/Watcher/Bot/Trigger.hs, src/Watcher/Bot/Types/Action.hs, watcher-bot.cabal
- When user has joined and not recognised as a spammer, schedule 5min delay check whether it was banned or not.
- Extend set with self-destructive messages for that purpose.
=> Schedule `getChatMember` check with 5-min delay

config/common/map.dhall, config/migrations/04-extend-user-context-for-unbans.dhall, scripts/start.sh, src/Telegram/Bot/API/Names.hs, src/Watcher/Bot.hs, src/Watcher/Bot/Cache.hs, src/Watcher/Bot/Handle.hs, src/Watcher/Bot/Handle/Ban.hs, src/Watcher/Bot/Handle/ChatMember.hs, src/Watcher/Bot/Handle/Message.hs, src/Watcher/Bot/Handle/Unban.hs, src/Watcher/Bot/State.hs, src/Watcher/Bot/Trigger.hs, src/Watcher/Bot/Types/Action.hs, src/Watcher/Bot/Types/UserInfo.hs, src/Watcher/Migration.hs, watcher-bot.cabal
- Extend `UserInfo` with username.
- Extend `UserMemberCheck` with `UserInfo`
- Extend `blocklist` with extra index where you can lookup `UserId` by username.
- To automate tedious process of migrations, implement migration worker which handles only the most recent migration via applying it for the most recent cache.
Closes #37.
=> Support unbans by username + migrations

config/migrations/04-extend-user-context-for-unbans.dhall
Well, Although it type-checked and tested locally, it produced some error on production.
=> hotfix: fix blocklist map type

src/Watcher/Bot/Handle/Unban.hs, src/Watcher/Bot/Reply.hs, src/Watcher/Bot/State.hs
In previous I forgot to add actual lookup for userId via username in unban process. This MR fixes it.
=> Lookup for username to obtiain `UserId` during unban

config/migrations/05-track-message-ids-in-quarantine.dhall, src/Watcher/Bot/Handle/Ban.hs, src/Watcher/Bot/Handle/Debug.hs, src/Watcher/Bot/Handle/Message.hs, src/Watcher/Bot/State/Chat.hs, src/Watcher/Orphans.hs
- Track message identifiers while user is in quarantine. In case of ban events, all of them should be removed too.
=> In case of ban remove all spammer's messages

config/default.dhall, src/Watcher/Bot/Handle/Ban.hs, src/Watcher/Bot/Handle/ChatMember.hs, src/Watcher/Bot/Handle/Message.hs, src/Watcher/Bot/Integration/CAS.hs, src/Watcher/Bot/Reply.hs, src/Watcher/Bot/Settings.hs, src/Watcher/Bot/State.hs, watcher-bot.cabal
- Settings with endpoint and timeout (which is not in use yet)
- Inject integration call:
- on join event (new chat member)
- on message in quarantine
- inside background chat members check
- Examples:
```
curl -X GET 'https://api.cas.chat/check?user_id=7596325892'
{"ok":true,"result":{"offenses":1,"messages":["Reward Vault:\n✔️ Single reward of 100 USDT\n✔️ Pair of 50 USDT rewards\n✔️ Trio of 30 USDT rewards \n✔️ Deca rewards of 10 USDT each\n\nTap the given link for your chance to snatch up these giveaways without spending a dim"],"time_added":"2024-12-16T10:14:01.000Z"}}
```
```
curl -X GET 'https://api.cas.chat/check?user_id=25650'
{"ok":false,"description":"Record not found."}
```
=> Add integration with CAS

src/Watcher/Bot/Handle/ChatMember.hs
Bot is being rate-limited with following messages:
```
[2024-12-27 10:43:22][Watcher][Info][build-server][PID 1453324][ThreadId 16] "Unexpected \"<!DOCTYPE html><html lang=\\\"en-\", expecting JSON value"
[2024-12-27 10:56:14][Watcher][Info][build-server][PID 1453324][ThreadId 16] "Unexpected \"<!DOCTYPE html><html lang=\\\"en-\", expecting JSON value"
[2024-12-27 10:58:11][Watcher][Info][build-server][PID 1453324][ThreadId 16] "Unexpected \"<!DOCTYPE html><html lang=\\\"en-\", expecting JSON value"
[2024-12-27 11:01:46][Watcher][Info][build-server][PID 1453324][ThreadId 16] "Unexpected \"<!DOCTYPE html><html lang=\\\"en-\", expecting JSON value"
[2024-12-27 11:04:50][Watcher][Info][build-server][PID 1453324][ThreadId 16] "Unexpected \"<!DOCTYPE html><html lang=\\\"en-\", expecting JSON …
```
=> Disable background CAS checks

src/Watcher/Bot/Analytics.hs, src/Watcher/Bot/Cache.hs, src/Watcher/Bot/Handle/Ban.hs, src/Watcher/Bot/State.hs, src/Watcher/Orphans.hs
All data has been restored via repl, logged events and pyrogram-based chat export. Few improvements captured in code:
- CSV parser for Event type and its fields.
- Keep 5 days of cache instead of a single one.
=> CSV Parser for `Event` + keep 5 days of cache

config/default.dhall, src/Watcher/Bot.hs, src/Watcher/Bot/Cache.hs, src/Watcher/Bot/Parse.hs, src/Watcher/Bot/Reply.hs, src/Watcher/Bot/Settings.hs, src/Watcher/Bot/Worker.hs, watcher-bot.cabal
- Extend cleanup job with backup capability: create TAR, compress it with `zstd` and publish to `#backups` topic.
- Extend `every` worker with one of two worker modes: time range during the day (right now only one range has supported) and bound to a specific time of day.
- Restore debug for owners group.
=> Nightly backups + scheduled workers + debug in owner's group

config/dictionary.dhall, src/Watcher/Bot/Handle/Message.hs
- A new spammer trend appears. 
- They provoke captcha bot to show their names and leave the group to prevent them being banned
- This PR handles checking of user names (not usernames) on chat_join event.
=> feat: analyse message of incoming users and try to ban them

.gitignore, config/default.dhall, scripts/gen-self-signed-cert.sh, src/Watcher/Bot.hs, src/Watcher/Bot/Settings.hs, src/Watcher/Bot/State.hs, watcher-bot.cabal
=> Draft: switch bot to webhook communication mode
